### PR TITLE
Improve build

### LINKED ISSUE #31: Cache .tox and possible apt packages
This is already done in the gitlab pipeline, we should also to it on github. Probably won't be totally trivial though

### PR DESCRIPTION
**Pull request by MischaPanch**
Closes #31 #22 

The caching is extra-careful: there is only one cache key which is pinned to the branch and to requirements.txt, setup.py and tox.ini. Any change in those files invalidate the previous cache

### CODE REVIEW

**Comment by MischaPanch** [comment]
Speedup due to caching is noticeable (below with the previous dependencies as benchmark). Since with this PR we get one more env and more dependencies, the speedup will be even higher

image

**Review by opcode81 — APPROVED** [review]
I can't test this because the tox build does not work under Windows.
I trust that you've verified the correctness, thus approved.
Just to clarify one thing: The relaxed depdendencies come in via the "full" specification in _extras_, i.e. this indirectly makes use of what we specified if setup.py - correct?

**Comment by MischaPanch** [comment]
> I can't test this because the tox build does not work under Windows.
> I trust that you've verified the correctness, thus approved.
> Just to clarify one thing: The relaxed depdendencies come in via the "full" specification in _extras_, i.e. this indirectly makes use of what we specified if setup.py - correct?

Precisely. This is done by omitting -rrequirements.txt in the dependencies of the tox env. Then it pulls the dependencies from setup.py

**Comment by MischaPanch** [comment]
Btw, you can see the correctness in the build logs. I have verified that in the new env the newest versions of the packages are installed

**Pull request merged**
